title: Page
tabs:
  content:
    label: Content
    icon: page
    fields:
      intro:
        label: Intro
        type:  textarea
      text:
        label: Text
        type:  textarea
  seo:
    labe: SEO
    icon: search
    fields:
      seo_title:
        label: SEO Title
        type: text
      seo_description:
        label: SEO Description
        type: textarea
        minlength: 50
        maxlength: 160
        buttons: false