title: Project
tabs:
  info:
    label: Infos
    icon: chart
    fields:
      title:
        label: Title
        type: text
        required: true
      author_name:
        label: Author's Name
        type: text
        width: 1/2
      author_nick:
        label: Author's Nick
        type: text
        width: 1/2
      brief:
        label: Brief/Short Description
        type: text
        required: true
      description:
        label: Description
        type: textarea
      publish_date:
        label: Published Date
        type: date
        display: YYYY-MM-DD
        width: 1/2
      update_date:
        label: Last Updated Date
        type: date
        display: YYYY-MM-DD
        width: 1/2
      os:
        label: Supported OS
        type: checkboxes
        options:
          windows: Windows
          macos: macOS
          linux: Linux
          android: Android
          ios: iOS
          other: Other
  links:
    label: Links
    icon: url
    fields:
      note:
        label: Note
        type: info
        text: |
          - The top three links will be shown on the project card
          - The top link will be styled as primary button
      sites:
        label: Links
        type: structure
        fields:
          type:
            label: Site Type
            type: select
            width: 1/4
            options:
              official: Official Site
              steam: Steam Store
              sfml: SFML Forum
              github: GitHub Repository
              tigsource: TIGSource Forum
              itch: itch.io Page
              gog: Good Old Games
              indiedb: IndieDB Page
              gamejolt: Game Jolt
              bitbucket: Bitbucket Repository
              gitlab: "GitLab Repository"
              switch: Nintendo Switch Store
              google: Play Store
              apple: App Store
              kickstarter: Kickstarter
          url:
            label: URL
            type: url
            width: 3/4
  media:
    label: Media
    icon: image
    columns:
      images:
        width: 2/3
        type: fields
        fields:
          title_img:
            label: Title Image
            type: files
            required: true
            query: page.images
            multiple: false
          screenshot_one:
            label: Screenshot 1
            type: files
            width: 1/3
            query: page.images
            multiple: false
          screenshot_two:
            label: Screenshot 2
            type: files
            width: 1/3
            query: page.images
            multiple: false
          screenshot_three:
            label: Screenshot 3
            type: files
            width: 1/3
            query: page.images
            multiple: false
          video_one:
            label: Video 1
            type: url
            width: 1/2
          video_two:
            label: Video 2
            type: url
            width: 1/2
      files:
        type: fields
        width: 1/3
        sections:
          files: true
  social:
    label: Social Media
    icon: twitter
    fields:
      twitter:
        label: Twitter Handle
        type: text
      youtube:
        label: YouTube Channel
        type: url
      facebook:
        label: Facebook
        type: url
  seo:
    label: SEO Overrides
    icon: search
    fields:
      seo_title:
        label: SEO Title
        type: text
      seo_description:
        label: SEO Description
        type: textarea
        minlength: 50
        maxlength: 160
        buttons: false
