title: Project

pages: false

files:
  fields:
    title:
      label: Title
      type: text
    caption:
      label: Caption
      type: textarea

fields:
  previewfiles:
    type: previewfiles

  project_infos:
    label: Project Infos
    type: headline
  title:
    label: Title
    type:  text
    required: true
  author_name:
    label: Author's Name
    type: text
    width: 1/2
  author_nick:
    label: Author's Nick
    type: text
    width: 1/2
  brief:
    label: Brief/Short Description
    type: text
    required: true
  description:
    label: Description
    type: textarea
  release_date:
    label: Release Date
    type: date
    format: DD.MM.YYYY
  os:
    label: Supported OS
    type: checkboxes
    options:
      windows: Windows
      macos: macOS
      linux: Linux
      android: Android
      ios: iOS
      other: Other

  project_links:
    label: Project Links
    type: headline
  offical_site:
    label: Official Site
    type: url
  steam:
    label: Steam Store/Community
    type: url
  sfml_forum:
    label: SFML Forum
    type: url
    width: 1/2
  tig_source:
    label: TIGSource Forum
    type: url
    width: 1/2
  itch_io:
    label: itch.io Page
    type: url
    width: 1/3
  indie_db:
    label: IndieDB Page
    type: url
    width: 1/3
  gamejolt:
    label: Game Jolt
    type: url
    width: 1/3
  github:
    label: GitHub Repository
    type: url
    width: 1/2
  bitbucket:
    label: Bitbucket Repository
    type: url
    width: 1/2
  custom_link_one_label:
    label: Custom Link Label
    type: text
    width: 1/4
  custom_link_one:
    label: Custom Link 1
    type: url
    width: 1/4
  custom_link_two_label:
    label: Custom Link Label
    type: text
    width: 1/4
  custom_link_two:
    label: Custom Link 2
    type: url
    width: 1/4
  brief_main:
    label: Brief Main Link
    type: select
    required: true
    width: 1/3
    options:
      offical_site: Official Website
      steam: Steam Store/Community
      sfml_forum: SFML Forum
      tig_source: TIGSource Forum
      itch_io: itch.io Page
      indie_db: IndieDB Page
      gamejolt: Game Jolt
      github: GitHub Repository
      bitbucket: Bitbucket Repository
      custom_link_one: Custom Link 1
      custom_link_two: Custom Link 2
  brief_second:
    label: Brief Second Link
    type: select
    width: 1/3
    options:
      offical_site: Official Website
      steam: Steam Store/Community
      sfml_forum: SFML Forum
      tig_source: TIGSource Forum
      itch_io: itch.io Page
      indie_db: IndieDB Page
      gamejolt: Game Jolt
      github: GitHub Repository
      bitbucket: Bitbucket Repository
      custom_link_one: Custom Link 1
      custom_link_two: Custom Link 2
  brief_third:
    label: Brief Third Link
    type: select
    width: 1/3
    options:
      offical_site: Official Website
      steam: Steam Store/Community
      sfml_forum: SFML Forum
      tig_source: TIGSource Forum
      itch_io: itch.io Page
      indie_db: IndieDB Page
      gamejolt: Game Jolt
      github: GitHub Repository
      bitbucket: Bitbucket Repository
      custom_link_one: Custom Link 1
      custom_link_two: Custom Link 2

  project_media:
    label: Project Media
    type: headline
  title_img:
    label: Title Image
    type: image
    required: true
  screenshot_one:
    label: Screenshot 1
    type: image
    width: 1/3
  screenshot_two:
    label: Screenshot 2
    type: image
    width: 1/3
  screenshot_three:
    label: Screenshot 3
    type: image
    width: 1/3
  video_one:
    label: Video 1
    type: url
    width: 1/2
  video_two:
    label: Video 2
    type: url
    width: 1/2

  project_social:
    label: Project Social Media
    type: headline
  twitter:
    label: Twitter Handle
    type: text
  youtube:
    label: YouTube Channel
    type: url
  facebook:
    label: Facebook
    type: url